root: dist

NestedSnippet:
  enabled: false

ImgWidthAndHeight:
  enabled: false

ConvertIncludeToRender:
  enabled: true

LiquidTag:
  enabled: false
  min_consecutive_statements: 10

MissingTemplate:
  enabled: true

AssetPreload:
  enabled: false

RequiredLayoutThemeObject:
  enabled: true

SpaceInsideBraces:
  enabled: true

ImgLazyLoading:
  enabled: false

DeprecateBgsizes:
  enabled: false

DeprecateLazysizes:
  enabled: false

SyntaxError:
  enabled: true

SchemaJsonFormat:
  enabled: false

TemplateLength:
  enabled: false
  max_length: 300

UnknownFilter:
  enabled: true

UnusedAssign:
  enabled: true

UnusedSnippet:
  enabled: true

MatchingSchemaTranslations:
  enabled: true

MatchingTranslations:
  enabled: true

DefaultLocale:
  enabled: true

TranslationKeyExists:
  enabled: true

ValidHTMLTranslation:
  enabled: true

ValidJson:
  enabled: true

ValidSchema:
  enabled: true

MissingRequiredTemplateFiles:
  enabled: true

UndefinedObject:
  enabled: true

RequiredDirectories:
  enabled: true

DeprecatedFilter:
  enabled: false