development:
  password: shptka_718efbb98aa8a4b8db1d62dc24beeee9
  theme_id: "165025677586"
  store: andrew-baklytsky.myshopify.com
  ignore_files:
#    - config/settings_data.json
#    - templates/*.json