[environments.dev]
theme = "176400826737"
store = "ccdc23"
password  = "shptka_85d1299255df3ca34319ec481e021b23"
ignore = ["templates/*.json", "sections/*.json", "config/settings_data.json"]
#live = true
#allow-live = true