[environments.production]
theme = 155766718602
password = "shptka_bdcfd95e071ac5beadd112673c7e8fb3"
store = "baklytsky-dev.myshopify.com"
ignore = [
    "config/settings_data.json",
    "sections/*.json",
    "templates/*.json",
    "templates/*.*.json",
    "templates/customers/.*.json"
]

#[environments.production]
#theme = 191648891250
#password = "shptka_8145e50fe846ff73dd2d6126b863afd7"
#store = "baklytsky-dev-2.myshopify.com"
#ignore = [
    #    "config/settings_data.json",
    #    "sections/*.json",
    #    "templates/*.json",
    #    "templates/*.*.json",
    #    "templates/customers/.*.json"
#]

#live = true
#allow-live = true