name: Deploy /dist to carbon-external

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.vscode/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        always-auth: true
        registry-url: https://npm.pkg.github.com/
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          'node_modules'
        key: ${{ runner.os }}-yarn-v3-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-v3-
    - run: yarn install
      env:
        NODE_AUTH_TOKEN: ${{secrets.ORG_PKG_READ}}
    - name: "Build external assets"
      run: yarn build:external

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        pwd

    - name: Remove existing carbon-external folder if it exists
      run: |
        if [ -d "carbon-external" ]; then
          rm -rf carbon-external
        fi

    - name: Clone target repository
      run: |
        cd ~/
        git clone git@github.com:presidiocreative/carbon-external.git carbon-external

    - name: Sync /dist contents to the root of carbon-external repository
      run: |
        # Ensure the dist folder exists
        if [ -d ~/work/carbon/carbon/dist ]; then
          rsync -av --delete --exclude '.git/' ~/work/carbon/carbon/dist/ ~/carbon-external/
        else
          echo "No dist folder found, skipping sync."
          exit 1
        fi
        # Commit and push changes
        cd ~/carbon-external
        git remote add dist https://x-access-token:${{ secrets.GH_PAT }}@github.com/presidiocreative/carbon-external.git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update files from /dist (commit $GITHUB_SHA)" || echo "No changes to commit"
        git push origin main