name: Deploy /dist to new-theme-dist

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.vscode/**'

jobs:
  deploy-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          pwd

      - name: Remove existing new-theme-dist folder if it exists
        run: |
          if [ -d "new-theme-dist" ]; then
            rm -rf new-theme-dist
          fi

      - name: Clone target repository
        run: |
          cd ~/
          git clone git@github.com:invisiblethemes/new-theme-dist.git new-theme-dist
          pwd

      - name: Sync /dist contents to the root of new-theme-dist
        run: |
          # Ensure the dist folder exists
          pwd
          if [ -d "dist" ]; then
            rsync -av --delete ~/work/new-theme/new-theme/dist/ ~/new-theme-dist/
          else
            echo "No dist folder found, skipping sync."
            exit 1
          fi
          # Commit and push changes
          cd ~/new-theme-dist
          echo "commit and push"
          pwd
          git remote set-url origin git@github.com:invisiblethemes/new-theme-dist.git
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update files from /dist (commit $GITHUB_SHA)" || echo "No changes to commit"
          git push origin main