name: zip-master
on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".vscode/**"
  workflow_dispatch:
jobs:
  cancel:
    name: "Cancel Previous Runs"
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          workflow_id: 10963554
  yarn:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
        cache: "yarn"
        always-auth: true
        registry-url: https://npm.pkg.github.com/
    - uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-v1-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-v1-
    - name: Yarn install
      run: yarn install --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{secrets.ORG_PKG_READ}}
  zip:
    needs: [yarn]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
        cache: "yarn"
    - uses: actions/cache@v3
      id: node_modules-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-v1-${{ hashFiles('yarn.lock') }}
        fail-on-cache-miss: true
    - uses: actions/cache@v3
      id: build-cache
      with:
        path: dist
        key: ${{ runner.os }}-dist-v1.4-${{ hashFiles('src/**/*', 'yarn.lock') }}
    - name: Zip Theme
      run: yarn zip
    - name: Ensure dist/ is not empty
      run: if [ -z "$(ls -A dist 2>/dev/null)" ]; then exit 1; fi
    - name: Ensure upload/ is not empty
      run: if [ -z "$(ls -A upload 2>/dev/null)" ]; then exit 1; fi
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ vars.THEME_NAME }}-dist
        path: dist/*
        retention-days: 5
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ vars.THEME_NAME }}-zip
        path: upload/*
        retention-days: 5
